\input texinfo	@c -*-texinfo-*-
@c %**start of header
@setfilename hac.info
@settitle The HAC Language
@c `on' is the default
@setchapternewpage odd
@c for two-sided book-style printing
@c %**end of header

@c "hac.texi"
@c $Id: hac.texi,v 1.2.2.1 2007/08/23 21:36:04 fang Exp $

@copying
This manual describes the HAC language specification.

Copyright @copyright{} 2007 Cornell University

@quotation
Published by ...
 
Permission is hereby granted to ...
@end quotation
@end copying

@c Title page and Copyright
@titlepage
@title The HAC Languge
@subtitle A boring technical document
@author David Fang
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ****************************** contents ************************************
@shortcontents
@contents

@ignore
@iftex
@node List of Figures
@unnumbered List of Figures
@listoffloats Figure
@end iftex
@end ignore

@c ****************************** Top *****************************************
@ifnottex
@node Top
@top The HAC Language
@insertcopying
@end ifnottex

@include hacmacros.texi

@c @copying is recommended here as well
@menu
* Preface::
* Goals::
* Introduction:: Introduction to HAC.
* Types::
* Expressions::
* Arrays::
* Processes::
* Channels::
* Datatypes::
* Namespaces::
* Templates::
* Connections::
* Typedefs::
* Linkage::
* CHP::
* PRS::
* SPEC Directives::
* Keywords::
* Grammar::
* Function Index::
* Concept Index::
@end menu

@c ****************************** chapter *************************************
@include chapters/preface.texi
@include chapters/goals.texi
@include chapters/intro.texi
@include chapters/types.texi
@include chapters/expressions.texi
@include chapters/arrays.texi
@include chapters/processes.texi
@include chapters/channels.texi
@include chapters/datatypes.texi
@include chapters/namespaces.texi
@include chapters/templates.texi
@include chapters/connections.texi
@include chapters/typedefs.texi
@include chapters/linkage.texi
@include chapters/CHP.texi
@include chapters/PRS.texi
@include chapters/SPEC.texi
@include grammar/keywords.texi
@include grammar/grammar.texi

@c ****************************** index ***************************************
@node Function Index
@unnumbered Function Index
@printindex fn

@node Concept Index
@unnumbered Concept Index
@printindex cp

@c ****************************** finis ***************************************
@bye

