\input texinfo	@c -*-texinfo-*-
@c %**start of header
@setfilename hacprsim.info
@settitle HACKT PRSIM Manual
@c `on' is the default
@setchapternewpage odd
@c for two-sided book-style printing
@c %**end of header

@c "prsim.texi"
@c $Id: hacprsim.texi,v 1.2 2007/10/08 19:09:36 fang Exp $

@dircategory Hierarchical Asynchronous Circuit Kompiler Toolkit (HACKT)
@direntry
* HAC PRSIM: (hacprsim).    HAC PRS Simulator.
@end direntry

@copying
This manual describes the usage and operation of HACKT's @command{prsim} 
simulator.  

Copyright @copyright{} 2007 Cornell University

@quotation
Published by ...
 
Permission is hereby granted to ...
@end quotation
@end copying

@c Title page and Copyright
@titlepage
@title HACKT PRSIM
@subtitle A simulator manual
@author David Fang
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ****************************** contents ************************************
@shortcontents
@contents

@ignore
@iftex
@node List of Figures
@unnumbered List of Figures
@listoffloats Figure
@end iftex
@end ignore

@c ****************************** Top *****************************************
@ifnottex
@node Top
@top PRSIM Manual Outline
@insertcopying
@end ifnottex

@c @copying is recommended here as well
@menu
* Introduction:: Introduction to PRSIM.
* Usage:: Command-line summary.
* Commands:: Interpreter commands.
* Execution:: How execution works.
* Command Index:: Interpreter commands.
@c * Variable Index:: Variables.
* Concept Index:: Concepts and terms.
@end menu

@c ****************************** chapter *************************************
@include intro.texi
@include usage.texi
@include commands.texi
@include execution.texi

@c ****************************** index ***************************************
@node Command Index
@unnumbered Command Index
@printindex fn

@ignore
@node Variable Index
@unnumbered Variable Index
@printindex vr
@end ignore

@node Concept Index
@unnumbered Concept Index
@printindex cp

@c ****************************** finis ***************************************
@bye

