
@node Test Chapter
@chapter Test Chapter
@cindex Sample index entry
@cindex Another sample index entry

Welcome to the first chapter.
This is just a file for experimenting with Texinfo commands.  

@noindent
TODO:
@itemize
@item
Learn Kung-fu.
@item
Learn to dodge bullets like in the Matrix.
@item
Graduate
@end itemize

@noindent
An enumerated list:
@enumerate
@item
Do you like bullets?
@item
Yes, I like bullets.
@item
Your days are numbered.
@end enumerate

I used @command{makeinfo} to generate this manual from the TexInfo source.
@TeX{} or @LaTeX{} typesets the printed manual into a PDF or PS.  

Here's an example of some random C++:

@example
#include <algorithm>       @r{// many useful STL gems}

using std::for_each;
@end example

@cartouche
@example
$ @kbd{echo $PATH}
/usr/local/bin:/usr/bin
@end example
@end cartouche

