/**
	\file "parser/hackt-union.h"
	Forawrd declarations needed to parse the YYSTYPE union
	defined in "parser/hackt-parse.h"
	$Id: hackt-union.h,v 1.3.4.1 2006/01/15 02:42:03 fang Exp $
	This file was formerly known as:
	Id: art++-union.h,v 1.1 2005/05/22 20:07:22 fang Exp
 */

#ifndef	__PARSER_HACKT_UNION_H__
#define	__PARSER_HACKT_UNION_H__

#include "AST/AST_fwd.h"
#include "AST/PRS_fwd.h"
#include "AST/HSE_fwd.h"
#include "AST/CHP_fwd.h"

using namespace HAC::parser;

// renaming functions to avoid collisions
// these symbol names are generated by the Makefile using awk scripts
#define	yy_union_lookup_dump		hackt__union_lookup_dump
#define	yy_union_resolve_dump		hackt__resolve_lookup_dump
#define	yy_union_lookup_delete		hackt__union_lookup_delete
#define	yy_union_resolve_delete		hackt__union_resolve_delete

#endif	// __PARSER_HACKT_UNION_H__ 

