/**
	\file "parser/instref-union.hh"
	Forawrd declarations needed to parse the YYSTYPE union
	defined in "parser/instref-parse.h"
	$Id: instref-union.hh,v 1.2 2006/01/22 06:53:25 fang Exp $
 */

#ifndef	__PARSER_INSTREF_UNION_H__
#define	__PARSER_INSTREF_UNION_H__

#include "AST/AST_fwd.hh"

using namespace HAC::parser;

// renaming functions to avoid collisions
// these symbol names are generated by the Makefile using awk scripts
#define	yy_union_lookup_dump		instref__union_lookup_dump
#define	yy_union_resolve_dump		instref__resolve_lookup_dump
#define	yy_union_lookup_delete		instref__union_lookup_delete
#define	yy_union_resolve_delete		instref__union_resolve_delete

#endif	// __PARSER_INSTREF_UNION_H__ 

