#!/usr/bin/awk -f
# "purify_flex.awk"
#	$Id: purify_flex.awk,v 1.1.2.1 2005/11/11 08:20:47 fang Exp $
# transforms calls to non-reentrant yylex into reentrant yylex, 
# generated by flex.  

# We accomplish this by declaring the lexer's state as a local object
# and passing it to the yylex routine.  
# The responsibility for hacking the yylex() call is elsewhere, 
# e.g. in a header file that redefines yylex() according to YYLEX_PARAM.

# this script works closely with "lexer/flex_lexer_state.h"

{
	if (match($0, "^yyparse\\(.*\\)")) {
		print;
		getline;	# expecting open brace
		print;
		# for now the name of the local state object is hard-coded
		print "flex::lexer_state _lexer_state;";
	} else {
		print;
	}
}

