/**
	\file "parser/spice-union.h"
	Forawrd declarations needed to parse the YYSTYPE union
	defined in "parser/spice-parse.h"
	$Id: spice-union.h,v 1.5 2006/02/04 06:43:22 fang Exp $
	This file was formerly known as:
	Id: art++-union.h,v 1.1 2005/05/22 20:07:22 fang Exp
 */

#ifndef	__PARSER_SPICE_UNION_H__
#define	__PARSER_SPICE_UNION_H__

#include "AST/AST_fwd.h"
#include "AST/PRS_fwd.h"
#include "AST/HSE_fwd.h"
#include "AST/CHP_fwd.h"
#include "AST/SPEC_fwd.h"

using namespace HAC::parser;

// renaming functions to avoid collisions
// these symbol names are generated by the Makefile using awk scripts
#define	yy_union_lookup_dump		spice__union_lookup_dump
#define	yy_union_resolve_dump		spice__resolve_lookup_dump
#define	yy_union_lookup_delete		spice__union_lookup_delete
#define	yy_union_resolve_delete		spice__union_resolve_delete

#endif	// __PARSER_SPICE_UNION_H__ 

