/**
	\file "parser/type-union.h"
	Forawrd declarations needed to parse the YYSTYPE union
	defined in "parser/type-parse.h"
	$Id: type-union.h,v 1.1 2006/07/30 05:50:12 fang Exp $
 */

#ifndef	__PARSER_TYPE_UNION_H__
#define	__PARSER_TYPE_UNION_H__

#include "AST/AST_fwd.h"

using namespace HAC::parser;

// renaming functions to avoid collisions
// these symbol names are generated by the Makefile using awk scripts
#define	yy_union_lookup_dump		type__union_lookup_dump
#define	yy_union_resolve_dump		type__resolve_lookup_dump
#define	yy_union_lookup_delete		type__union_lookup_delete
#define	yy_union_resolve_delete		type__union_resolve_delete

#endif	// __PARSER_TYPE_UNION_H__ 

