@c "chapters/expressions.texi"
@c $Id: expressions.texi,v 1.4 2011/04/05 18:26:19 fang Exp $

@node Expressions
@chapter Expressions
@cindex expressions
@cindex meta-expressions

Expressions live in the realm of parameters and datatypes.  
Compile-time meta language.  

Boolean.

Integer.

Real.

String.

@menu
* Range expressions::
* Function expressions::
@end menu

@c ----------------------------------------------------------------------------
@node Range expressions
@section Range expressions
@cindex range expressions

Limits: interpretation of negative ranges?
Are we allowing negative indices?

Implicit ranges.

Explicit ranges.
Q: does @math{x<=y}?
If we allow negative indices then yes, because we need to be able 
to express empty ranges, when @math{x>y}.

Compile-time (meta-language) interpretation.  

See chapter on compile-time flow-control (loops and conditionals).  


@c ----------------------------------------------------------------------------
@node Function expressions
@section Function expressions
@cindex function expressions

The @HAC{} language supports function calls in expressions.
Supported argument types and return types include integer, boolean, 
real (float, double), and strings.  

@include fn/strcat.texi
@include fn/cond.texi
@include fn/minmax.texi
@include fn/strtox.texi
@include fn/rtoz.texi
@include fn/ztor.texi
@include fn/math.texi

